import Topbar from '@/components/shared/topbar'
import '../globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import LeftSidebar from '@/components/shared/left-sidebar'
import RightSidebar from '@/components/shared/right-sidebar'
import Bottombar from '@/components/shared/bottombar'
export const metadata = {
  title: 'Threads',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <Topbar />
          <main className='flex'>
            <LeftSidebar />
            <section className='main-container'>
              <div className='w-full max-w-4xl'> 
                {children}
              </div>
            </section>

            <RightSidebar />
          </main>

          <Bottombar />
        </body>
      </html>
    </ClerkProvider>
  )
}
